Repository 2nd-year/ITP-BackEnd, pull requests merged in 2022-03, with the labels that each got.

#25 Implement student routes, validations and controllers
  index.js
  package-lock.json
  src/controllers/student.controller.js
  src/controllers/teacher.controller.js
  src/model/StudentAccountModel.js
  src/routes/student.js
  src/validations/studentValidation.js
Labels: enhancement

#28 Admin register
  index.js
  package-lock.json
  src/controllers/admin.controller.js
  src/model/SystemAdminModel.js
  src/routes/admin.js
  src/validations/adminValidation.js
Labels: enhancement, Feature

#29 implement Event register
  index.js
  package-lock.json
  src/controllers/event.controller.js
  src/controllers/student.controller.js
  src/controllers/teacher.controller.js
  src/model/EventModel.js
  src/model/StudentAccountModel.js
  src/routes/event.js
  src/routes/student.js
  src/validations/eventValidation.js
  src/validations/studentValidation.js
Labels: enhancement, Feature

#31 Implement exam create and read functions
  index.js
  src/controllers/exam.controller.js
  src/routes/exam.js
  src/routes/student.js
  src/validations/examValidation.js
Labels: enhancement, Feature

#37 Tutorial function implementation
  index.js
  package-lock.json
  src/controllers/tutorial.controller.js
  src/model/TutorialModels.js
  src/routes/tutorial.js
  src/validations/tutorialValidation.js
Labels: enhancement, Feature

#34 Implement event create and get functions
  src/controllers/event.controller.js
  src/routes/event.js
  src/validations/eventValidation.js
Labels: enhancement, Feature

#35 implementing Time table and inventory functions
  index.js
  src/controllers/inventory.controller.js
  src/controllers/timetable.controller.js
  src/model/InventoryModel.js
  src/model/TimetableModels.js
  src/routes/inventory.js
  src/routes/timetable.js
  src/validations/inventoryValidation.js
  src/validations/timetableValidation.js
Labels: enhancement, Feature

#38 Implement result Create and get functions
  index.js
  src/controllers/result.controller.js
  src/model/ResultModel.js
  src/routes/result.js
  src/validations/resultValidation.js
Labels: enhancement, Feature

#41 Get tutorial implementation
  src/controllers/tutorial.controller.js
  src/routes/tutorial.js
Labels: enhancement, Feature

#43 Event update and delete
  src/controllers/event.controller.js
  src/routes/event.js
  src/validations/eventValidation.js
Labels: enhancement, Feature

#49 Admin update and delete
  src/controllers/admin.controller.js
  src/routes/admin.js
  src/validations/adminValidation.js
Labels: enhancement, Feature

#50 Teacher update and delete
  index.js
  src/controllers/event.controller.js
  src/controllers/teacher.controller.js
  src/model/TeacherModel.js
  src/routes/Teacher.js
  src/routes/event.js
  src/routes/teacher.js
  src/validations/teacherValidation.js
Labels: enhancement, Feature

#42 Implement lecture hall create and get function
  index.js
  src/controllers/Hall.controller.js
  src/controllers/event.controller.js
  src/model/HallModel.js
  src/routes/Hall.js
  src/validations/HallValidation.js
Labels: enhancement, Feature

#21 Teacher create
  index.js
  src/controllers/event.controller.js
  src/controllers/teacher.controller.js
  src/model/TeacherModel.js
  src/routes/Teacher.js
  src/routes/event.js
  src/routes/teacher.js
  src/validations/teacherValidation.js
Labels: enhancement, High priority

#60 Event register
  src/controllers/event.controller.js
  src/routes/event.js
Labels: enhancement

#52 Time table model
  src/controllers/inventory.controller.js
  src/controllers/timetable.controller.js
  src/model/InventoryModel.js
  src/routes/inventory.js
  src/routes/timetable.js
  src/validations/inventoryValidation.js
Labels: enhancement

#63 implement getone Timetable and Inventory
  src/controllers/inventory.controller.js
  src/controllers/timetable.controller.js
  src/routes/inventory.js
  src/routes/timetable.js
Labels: enhancement

#62 implement update delete getone Hall
  src/controllers/Hall.controller.js
  src/routes/Hall.js
Labels: enhancement

#64 Implement exam, result Update, Delete, getone functions & login
  .gitignore
  index.js
  package-lock.json
  package.json
  src/controllers/exam.controller.js
  src/controllers/login.contorller.js
  src/controllers/result.controller.js
  src/model/ResultModel.js
  src/routes/exam.js
  src/routes/login.js
  src/routes/result.js
  src/validations/loginValidation.js
  src/validations/resultValidation.js
  src/verifyToken/verifyToken.js
Labels: enhancement, Feature

#65 Implement update, delete, getOne functions.
  src/controllers/tutorial.controller.js
  src/routes/tutorial.js
Labels: enhancement

#72 protect the routes
  src/controllers/exam.controller.js
  src/controllers/login.contorller.js
  src/controllers/result.controller.js
  src/routes/exam.js
  src/routes/login.js
  src/routes/result.js
  src/verifyToken/verifyToken.js
Labels: enhancement, Feature

#75 define routes as private
  src/controllers/event.controller.js
Labels: enhancement, Feature

#74 define routes as private
  src/controllers/inventory.controller.js
  src/controllers/timetable.controller.js
Labels: enhancement, Feature
